# Generated by Django 5.0.4 on 2024-04-27 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('Title', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('Slug', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=50)),
                ('Slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.blogcontent')),
            ],
        ),
    ]
